/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlumniConnectRouteImport } from './routes/alumni-connect'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MandatoryDisclosureRouteImport } from './routes/mandatory-disclosure'
import { Route as AboutAdvisoryBoardRouteImport } from './routes/about.advisory-board'
import { Route as AboutFoundersVisionRouteImport } from './routes/about.founders-vision'
import { Route as AboutHistoryRouteImport } from './routes/about.history'
import { Route as AboutPrincipalsMessageRouteImport } from './routes/about.principals-message'
import { Route as AboutTestimonialsRouteImport } from './routes/about.testimonials'
import { Route as AboutVisionMissionRouteImport } from './routes/about.vision-mission'
import { Route as AcademicsCurriculumRouteImport } from './routes/academics.curriculum'
import { Route as AcademicsMethodOfEvaluationRouteImport } from './routes/academics.method-of-evaluation'
import { Route as AcademicsOnlineLearningRouteImport } from './routes/academics.online-learning'
import { Route as AcademicsTeachingMethodologyRouteImport } from './routes/academics.teaching-methodology'
import { Route as AdmissionsFaqsRouteImport } from './routes/admissions.faqs'
import { Route as AdmissionsOnlineRegistrationRouteImport } from './routes/admissions.online-registration'
import { Route as LifeAchievementsRouteImport } from './routes/life.achievements'
import { Route as LifeGalleryRouteImport } from './routes/life.gallery'
import { Route as LifeInfrastructureRouteImport } from './routes/life.infrastructure'
import { Route as LifeStudentClubsRouteImport } from './routes/life.student-clubs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniConnectRoute = AlumniConnectRouteImport.update({
  id: '/alumni-connect',
  path: '/alumni-connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MandatoryDisclosureRoute = MandatoryDisclosureRouteImport.update({
  id: '/mandatory-disclosure',
  path: '/mandatory-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutAdvisoryBoardRoute = AboutAdvisoryBoardRouteImport.update({
  id: '/about/advisory-board',
  path: '/about/advisory-board',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutFoundersVisionRoute = AboutFoundersVisionRouteImport.update({
  id: '/about/founders-vision',
  path: '/about/founders-vision',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutHistoryRoute = AboutHistoryRouteImport.update({
  id: '/about/history',
  path: '/about/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPrincipalsMessageRoute = AboutPrincipalsMessageRouteImport.update({
  id: '/about/principals-message',
  path: '/about/principals-message',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTestimonialsRoute = AboutTestimonialsRouteImport.update({
  id: '/about/testimonials',
  path: '/about/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutVisionMissionRoute = AboutVisionMissionRouteImport.update({
  id: '/about/vision-mission',
  path: '/about/vision-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsCurriculumRoute = AcademicsCurriculumRouteImport.update({
  id: '/academics/curriculum',
  path: '/academics/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsMethodOfEvaluationRoute =
  AcademicsMethodOfEvaluationRouteImport.update({
    id: '/academics/method-of-evaluation',
    path: '/academics/method-of-evaluation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademicsOnlineLearningRoute = AcademicsOnlineLearningRouteImport.update({
  id: '/academics/online-learning',
  path: '/academics/online-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsTeachingMethodologyRoute =
  AcademicsTeachingMethodologyRouteImport.update({
    id: '/academics/teaching-methodology',
    path: '/academics/teaching-methodology',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdmissionsFaqsRoute = AdmissionsFaqsRouteImport.update({
  id: '/admissions/faqs',
  path: '/admissions/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsOnlineRegistrationRoute =
  AdmissionsOnlineRegistrationRouteImport.update({
    id: '/admissions/online-registration',
    path: '/admissions/online-registration',
    getParentRoute: () => rootRouteImport,
  } as any)
const LifeAchievementsRoute = LifeAchievementsRouteImport.update({
  id: '/life/achievements',
  path: '/life/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeGalleryRoute = LifeGalleryRouteImport.update({
  id: '/life/gallery',
  path: '/life/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeInfrastructureRoute = LifeInfrastructureRouteImport.update({
  id: '/life/infrastructure',
  path: '/life/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeStudentClubsRoute = LifeStudentClubsRouteImport.update({
  id: '/life/student-clubs',
  path: '/life/student-clubs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alumni-connect': typeof AlumniConnectRoute
  '/contact': typeof ContactRoute
  '/mandatory-disclosure': typeof MandatoryDisclosureRoute
  '/about/advisory-board': typeof AboutAdvisoryBoardRoute
  '/about/founders-vision': typeof AboutFoundersVisionRoute
  '/about/history': typeof AboutHistoryRoute
  '/about/principals-message': typeof AboutPrincipalsMessageRoute
  '/about/testimonials': typeof AboutTestimonialsRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/academics/curriculum': typeof AcademicsCurriculumRoute
  '/academics/method-of-evaluation': typeof AcademicsMethodOfEvaluationRoute
  '/academics/online-learning': typeof AcademicsOnlineLearningRoute
  '/academics/teaching-methodology': typeof AcademicsTeachingMethodologyRoute
  '/admissions/faqs': typeof AdmissionsFaqsRoute
  '/admissions/online-registration': typeof AdmissionsOnlineRegistrationRoute
  '/life/achievements': typeof LifeAchievementsRoute
  '/life/gallery': typeof LifeGalleryRoute
  '/life/infrastructure': typeof LifeInfrastructureRoute
  '/life/student-clubs': typeof LifeStudentClubsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alumni-connect': typeof AlumniConnectRoute
  '/contact': typeof ContactRoute
  '/mandatory-disclosure': typeof MandatoryDisclosureRoute
  '/about/advisory-board': typeof AboutAdvisoryBoardRoute
  '/about/founders-vision': typeof AboutFoundersVisionRoute
  '/about/history': typeof AboutHistoryRoute
  '/about/principals-message': typeof AboutPrincipalsMessageRoute
  '/about/testimonials': typeof AboutTestimonialsRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/academics/curriculum': typeof AcademicsCurriculumRoute
  '/academics/method-of-evaluation': typeof AcademicsMethodOfEvaluationRoute
  '/academics/online-learning': typeof AcademicsOnlineLearningRoute
  '/academics/teaching-methodology': typeof AcademicsTeachingMethodologyRoute
  '/admissions/faqs': typeof AdmissionsFaqsRoute
  '/admissions/online-registration': typeof AdmissionsOnlineRegistrationRoute
  '/life/achievements': typeof LifeAchievementsRoute
  '/life/gallery': typeof LifeGalleryRoute
  '/life/infrastructure': typeof LifeInfrastructureRoute
  '/life/student-clubs': typeof LifeStudentClubsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alumni-connect': typeof AlumniConnectRoute
  '/contact': typeof ContactRoute
  '/mandatory-disclosure': typeof MandatoryDisclosureRoute
  '/about/advisory-board': typeof AboutAdvisoryBoardRoute
  '/about/founders-vision': typeof AboutFoundersVisionRoute
  '/about/history': typeof AboutHistoryRoute
  '/about/principals-message': typeof AboutPrincipalsMessageRoute
  '/about/testimonials': typeof AboutTestimonialsRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/academics/curriculum': typeof AcademicsCurriculumRoute
  '/academics/method-of-evaluation': typeof AcademicsMethodOfEvaluationRoute
  '/academics/online-learning': typeof AcademicsOnlineLearningRoute
  '/academics/teaching-methodology': typeof AcademicsTeachingMethodologyRoute
  '/admissions/faqs': typeof AdmissionsFaqsRoute
  '/admissions/online-registration': typeof AdmissionsOnlineRegistrationRoute
  '/life/achievements': typeof LifeAchievementsRoute
  '/life/gallery': typeof LifeGalleryRoute
  '/life/infrastructure': typeof LifeInfrastructureRoute
  '/life/student-clubs': typeof LifeStudentClubsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alumni-connect'
    | '/contact'
    | '/mandatory-disclosure'
    | '/about/advisory-board'
    | '/about/founders-vision'
    | '/about/history'
    | '/about/principals-message'
    | '/about/testimonials'
    | '/about/vision-mission'
    | '/academics/curriculum'
    | '/academics/method-of-evaluation'
    | '/academics/online-learning'
    | '/academics/teaching-methodology'
    | '/admissions/faqs'
    | '/admissions/online-registration'
    | '/life/achievements'
    | '/life/gallery'
    | '/life/infrastructure'
    | '/life/student-clubs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alumni-connect'
    | '/contact'
    | '/mandatory-disclosure'
    | '/about/advisory-board'
    | '/about/founders-vision'
    | '/about/history'
    | '/about/principals-message'
    | '/about/testimonials'
    | '/about/vision-mission'
    | '/academics/curriculum'
    | '/academics/method-of-evaluation'
    | '/academics/online-learning'
    | '/academics/teaching-methodology'
    | '/admissions/faqs'
    | '/admissions/online-registration'
    | '/life/achievements'
    | '/life/gallery'
    | '/life/infrastructure'
    | '/life/student-clubs'
  id:
    | '__root__'
    | '/'
    | '/alumni-connect'
    | '/contact'
    | '/mandatory-disclosure'
    | '/about/advisory-board'
    | '/about/founders-vision'
    | '/about/history'
    | '/about/principals-message'
    | '/about/testimonials'
    | '/about/vision-mission'
    | '/academics/curriculum'
    | '/academics/method-of-evaluation'
    | '/academics/online-learning'
    | '/academics/teaching-methodology'
    | '/admissions/faqs'
    | '/admissions/online-registration'
    | '/life/achievements'
    | '/life/gallery'
    | '/life/infrastructure'
    | '/life/student-clubs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlumniConnectRoute: typeof AlumniConnectRoute
  ContactRoute: typeof ContactRoute
  MandatoryDisclosureRoute: typeof MandatoryDisclosureRoute
  AboutAdvisoryBoardRoute: typeof AboutAdvisoryBoardRoute
  AboutFoundersVisionRoute: typeof AboutFoundersVisionRoute
  AboutHistoryRoute: typeof AboutHistoryRoute
  AboutPrincipalsMessageRoute: typeof AboutPrincipalsMessageRoute
  AboutTestimonialsRoute: typeof AboutTestimonialsRoute
  AboutVisionMissionRoute: typeof AboutVisionMissionRoute
  AcademicsCurriculumRoute: typeof AcademicsCurriculumRoute
  AcademicsMethodOfEvaluationRoute: typeof AcademicsMethodOfEvaluationRoute
  AcademicsOnlineLearningRoute: typeof AcademicsOnlineLearningRoute
  AcademicsTeachingMethodologyRoute: typeof AcademicsTeachingMethodologyRoute
  AdmissionsFaqsRoute: typeof AdmissionsFaqsRoute
  AdmissionsOnlineRegistrationRoute: typeof AdmissionsOnlineRegistrationRoute
  LifeAchievementsRoute: typeof LifeAchievementsRoute
  LifeGalleryRoute: typeof LifeGalleryRoute
  LifeInfrastructureRoute: typeof LifeInfrastructureRoute
  LifeStudentClubsRoute: typeof LifeStudentClubsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni-connect': {
      id: '/alumni-connect'
      path: '/alumni-connect'
      fullPath: '/alumni-connect'
      preLoaderRoute: typeof AlumniConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mandatory-disclosure': {
      id: '/mandatory-disclosure'
      path: '/mandatory-disclosure'
      fullPath: '/mandatory-disclosure'
      preLoaderRoute: typeof MandatoryDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/advisory-board': {
      id: '/about/advisory-board'
      path: '/about/advisory-board'
      fullPath: '/about/advisory-board'
      preLoaderRoute: typeof AboutAdvisoryBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/founders-vision': {
      id: '/about/founders-vision'
      path: '/about/founders-vision'
      fullPath: '/about/founders-vision'
      preLoaderRoute: typeof AboutFoundersVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/history': {
      id: '/about/history'
      path: '/about/history'
      fullPath: '/about/history'
      preLoaderRoute: typeof AboutHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/principals-message': {
      id: '/about/principals-message'
      path: '/about/principals-message'
      fullPath: '/about/principals-message'
      preLoaderRoute: typeof AboutPrincipalsMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/testimonials': {
      id: '/about/testimonials'
      path: '/about/testimonials'
      fullPath: '/about/testimonials'
      preLoaderRoute: typeof AboutTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/vision-mission': {
      id: '/about/vision-mission'
      path: '/about/vision-mission'
      fullPath: '/about/vision-mission'
      preLoaderRoute: typeof AboutVisionMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/curriculum': {
      id: '/academics/curriculum'
      path: '/academics/curriculum'
      fullPath: '/academics/curriculum'
      preLoaderRoute: typeof AcademicsCurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/method-of-evaluation': {
      id: '/academics/method-of-evaluation'
      path: '/academics/method-of-evaluation'
      fullPath: '/academics/method-of-evaluation'
      preLoaderRoute: typeof AcademicsMethodOfEvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/online-learning': {
      id: '/academics/online-learning'
      path: '/academics/online-learning'
      fullPath: '/academics/online-learning'
      preLoaderRoute: typeof AcademicsOnlineLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/teaching-methodology': {
      id: '/academics/teaching-methodology'
      path: '/academics/teaching-methodology'
      fullPath: '/academics/teaching-methodology'
      preLoaderRoute: typeof AcademicsTeachingMethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/faqs': {
      id: '/admissions/faqs'
      path: '/admissions/faqs'
      fullPath: '/admissions/faqs'
      preLoaderRoute: typeof AdmissionsFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/online-registration': {
      id: '/admissions/online-registration'
      path: '/admissions/online-registration'
      fullPath: '/admissions/online-registration'
      preLoaderRoute: typeof AdmissionsOnlineRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life/achievements': {
      id: '/life/achievements'
      path: '/life/achievements'
      fullPath: '/life/achievements'
      preLoaderRoute: typeof LifeAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life/gallery': {
      id: '/life/gallery'
      path: '/life/gallery'
      fullPath: '/life/gallery'
      preLoaderRoute: typeof LifeGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life/infrastructure': {
      id: '/life/infrastructure'
      path: '/life/infrastructure'
      fullPath: '/life/infrastructure'
      preLoaderRoute: typeof LifeInfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life/student-clubs': {
      id: '/life/student-clubs'
      path: '/life/student-clubs'
      fullPath: '/life/student-clubs'
      preLoaderRoute: typeof LifeStudentClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlumniConnectRoute: AlumniConnectRoute,
  ContactRoute: ContactRoute,
  MandatoryDisclosureRoute: MandatoryDisclosureRoute,
  AboutAdvisoryBoardRoute: AboutAdvisoryBoardRoute,
  AboutFoundersVisionRoute: AboutFoundersVisionRoute,
  AboutHistoryRoute: AboutHistoryRoute,
  AboutPrincipalsMessageRoute: AboutPrincipalsMessageRoute,
  AboutTestimonialsRoute: AboutTestimonialsRoute,
  AboutVisionMissionRoute: AboutVisionMissionRoute,
  AcademicsCurriculumRoute: AcademicsCurriculumRoute,
  AcademicsMethodOfEvaluationRoute: AcademicsMethodOfEvaluationRoute,
  AcademicsOnlineLearningRoute: AcademicsOnlineLearningRoute,
  AcademicsTeachingMethodologyRoute: AcademicsTeachingMethodologyRoute,
  AdmissionsFaqsRoute: AdmissionsFaqsRoute,
  AdmissionsOnlineRegistrationRoute: AdmissionsOnlineRegistrationRoute,
  LifeAchievementsRoute: LifeAchievementsRoute,
  LifeGalleryRoute: LifeGalleryRoute,
  LifeInfrastructureRoute: LifeInfrastructureRoute,
  LifeStudentClubsRoute: LifeStudentClubsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
