/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlumniConnectRouteImport } from './routes/alumni-connect'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MandatoryDisclosureRouteImport } from './routes/mandatory-disclosure'
import { Route as AboutAdvisoryBoardRouteImport } from './routes/about.advisory-board'
import { Route as AboutFacilitiesRouteImport } from './routes/about.facilities'
import { Route as AboutFoundersVisionRouteImport } from './routes/about.founders-vision'
import { Route as AboutHistoryRouteImport } from './routes/about.history'
import { Route as AboutManagingCommitteeRouteImport } from './routes/about.managing-committee'
import { Route as AboutPrincipalsMessageRouteImport } from './routes/about.principals-message'
import { Route as AboutTestimonialsRouteImport } from './routes/about.testimonials'
import { Route as AboutVisionMissionRouteImport } from './routes/about.vision-mission'
import { Route as AcademicsActivityScheduleRouteImport } from './routes/academics.activity-schedule'
import { Route as AcademicsCurriculumRouteImport } from './routes/academics.curriculum'
import { Route as AcademicsExaminationRouteImport } from './routes/academics.examination'
import { Route as AcademicsMethodOfEvaluationRouteImport } from './routes/academics.method-of-evaluation'
import { Route as AcademicsOnlineLearningRouteImport } from './routes/academics.online-learning'
import { Route as AcademicsTeachingMethodologyRouteImport } from './routes/academics.teaching-methodology'
import { Route as AdmissionsFaqsRouteImport } from './routes/admissions.faqs'
import { Route as AdmissionsFeeRouteImport } from './routes/admissions.fee'
import { Route as AdmissionsOnlineRegistrationRouteImport } from './routes/admissions.online-registration'
import { Route as AdmissionsPortalRouteImport } from './routes/admissions.portal'
import { Route as AdmissionsUniformRouteImport } from './routes/admissions.uniform'
import { Route as EventsAksharaAbhyasRouteImport } from './routes/events.akshara-abhyas'
import { Route as EventsAnnualDayRouteImport } from './routes/events.annual-day'
import { Route as EventsFancyDressRouteImport } from './routes/events.fancy-dress'
import { Route as EventsIndependenceDayRouteImport } from './routes/events.independence-day'
import { Route as EventsPrimaryAnnualDayRouteImport } from './routes/events.primary-annual-day'
import { Route as EventsPrimarySportsDayRouteImport } from './routes/events.primary-sports-day'
import { Route as EventsProjectDayRouteImport } from './routes/events.project-day'
import { Route as EventsRepublicDayRouteImport } from './routes/events.republic-day'
import { Route as EventsSportsDayRouteImport } from './routes/events.sports-day'
import { Route as EventsVidhyaPraveshRouteImport } from './routes/events.vidhya-pravesh'
import { Route as LifeAchievementsRouteImport } from './routes/life.achievements'
import { Route as LifeGalleryRouteImport } from './routes/life.gallery'
import { Route as LifeInfrastructureRouteImport } from './routes/life.infrastructure'
import { Route as LifeStudentClubsRouteImport } from './routes/life.student-clubs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniConnectRoute = AlumniConnectRouteImport.update({
  id: '/alumni-connect',
  path: '/alumni-connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MandatoryDisclosureRoute = MandatoryDisclosureRouteImport.update({
  id: '/mandatory-disclosure',
  path: '/mandatory-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutAdvisoryBoardRoute = AboutAdvisoryBoardRouteImport.update({
  id: '/about/advisory-board',
  path: '/about/advisory-board',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutFacilitiesRoute = AboutFacilitiesRouteImport.update({
  id: '/about/facilities',
  path: '/about/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutFoundersVisionRoute = AboutFoundersVisionRouteImport.update({
  id: '/about/founders-vision',
  path: '/about/founders-vision',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutHistoryRoute = AboutHistoryRouteImport.update({
  id: '/about/history',
  path: '/about/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutManagingCommitteeRoute = AboutManagingCommitteeRouteImport.update({
  id: '/about/managing-committee',
  path: '/about/managing-committee',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPrincipalsMessageRoute = AboutPrincipalsMessageRouteImport.update({
  id: '/about/principals-message',
  path: '/about/principals-message',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTestimonialsRoute = AboutTestimonialsRouteImport.update({
  id: '/about/testimonials',
  path: '/about/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutVisionMissionRoute = AboutVisionMissionRouteImport.update({
  id: '/about/vision-mission',
  path: '/about/vision-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsActivityScheduleRoute =
  AcademicsActivityScheduleRouteImport.update({
    id: '/academics/activity-schedule',
    path: '/academics/activity-schedule',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademicsCurriculumRoute = AcademicsCurriculumRouteImport.update({
  id: '/academics/curriculum',
  path: '/academics/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsExaminationRoute = AcademicsExaminationRouteImport.update({
  id: '/academics/examination',
  path: '/academics/examination',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsMethodOfEvaluationRoute =
  AcademicsMethodOfEvaluationRouteImport.update({
    id: '/academics/method-of-evaluation',
    path: '/academics/method-of-evaluation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademicsOnlineLearningRoute = AcademicsOnlineLearningRouteImport.update({
  id: '/academics/online-learning',
  path: '/academics/online-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsTeachingMethodologyRoute =
  AcademicsTeachingMethodologyRouteImport.update({
    id: '/academics/teaching-methodology',
    path: '/academics/teaching-methodology',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdmissionsFaqsRoute = AdmissionsFaqsRouteImport.update({
  id: '/admissions/faqs',
  path: '/admissions/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsFeeRoute = AdmissionsFeeRouteImport.update({
  id: '/admissions/fee',
  path: '/admissions/fee',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsOnlineRegistrationRoute =
  AdmissionsOnlineRegistrationRouteImport.update({
    id: '/admissions/online-registration',
    path: '/admissions/online-registration',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdmissionsPortalRoute = AdmissionsPortalRouteImport.update({
  id: '/admissions/portal',
  path: '/admissions/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsUniformRoute = AdmissionsUniformRouteImport.update({
  id: '/admissions/uniform',
  path: '/admissions/uniform',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsAksharaAbhyasRoute = EventsAksharaAbhyasRouteImport.update({
  id: '/events/akshara-abhyas',
  path: '/events/akshara-abhyas',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsAnnualDayRoute = EventsAnnualDayRouteImport.update({
  id: '/events/annual-day',
  path: '/events/annual-day',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsFancyDressRoute = EventsFancyDressRouteImport.update({
  id: '/events/fancy-dress',
  path: '/events/fancy-dress',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndependenceDayRoute = EventsIndependenceDayRouteImport.update({
  id: '/events/independence-day',
  path: '/events/independence-day',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsPrimaryAnnualDayRoute = EventsPrimaryAnnualDayRouteImport.update({
  id: '/events/primary-annual-day',
  path: '/events/primary-annual-day',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsPrimarySportsDayRoute = EventsPrimarySportsDayRouteImport.update({
  id: '/events/primary-sports-day',
  path: '/events/primary-sports-day',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsProjectDayRoute = EventsProjectDayRouteImport.update({
  id: '/events/project-day',
  path: '/events/project-day',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRepublicDayRoute = EventsRepublicDayRouteImport.update({
  id: '/events/republic-day',
  path: '/events/republic-day',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSportsDayRoute = EventsSportsDayRouteImport.update({
  id: '/events/sports-day',
  path: '/events/sports-day',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsVidhyaPraveshRoute = EventsVidhyaPraveshRouteImport.update({
  id: '/events/vidhya-pravesh',
  path: '/events/vidhya-pravesh',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeAchievementsRoute = LifeAchievementsRouteImport.update({
  id: '/life/achievements',
  path: '/life/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeGalleryRoute = LifeGalleryRouteImport.update({
  id: '/life/gallery',
  path: '/life/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeInfrastructureRoute = LifeInfrastructureRouteImport.update({
  id: '/life/infrastructure',
  path: '/life/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeStudentClubsRoute = LifeStudentClubsRouteImport.update({
  id: '/life/student-clubs',
  path: '/life/student-clubs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alumni-connect': typeof AlumniConnectRoute
  '/contact': typeof ContactRoute
  '/mandatory-disclosure': typeof MandatoryDisclosureRoute
  '/about/advisory-board': typeof AboutAdvisoryBoardRoute
  '/about/facilities': typeof AboutFacilitiesRoute
  '/about/founders-vision': typeof AboutFoundersVisionRoute
  '/about/history': typeof AboutHistoryRoute
  '/about/managing-committee': typeof AboutManagingCommitteeRoute
  '/about/principals-message': typeof AboutPrincipalsMessageRoute
  '/about/testimonials': typeof AboutTestimonialsRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/academics/activity-schedule': typeof AcademicsActivityScheduleRoute
  '/academics/curriculum': typeof AcademicsCurriculumRoute
  '/academics/examination': typeof AcademicsExaminationRoute
  '/academics/method-of-evaluation': typeof AcademicsMethodOfEvaluationRoute
  '/academics/online-learning': typeof AcademicsOnlineLearningRoute
  '/academics/teaching-methodology': typeof AcademicsTeachingMethodologyRoute
  '/admissions/faqs': typeof AdmissionsFaqsRoute
  '/admissions/fee': typeof AdmissionsFeeRoute
  '/admissions/online-registration': typeof AdmissionsOnlineRegistrationRoute
  '/admissions/portal': typeof AdmissionsPortalRoute
  '/admissions/uniform': typeof AdmissionsUniformRoute
  '/events/akshara-abhyas': typeof EventsAksharaAbhyasRoute
  '/events/annual-day': typeof EventsAnnualDayRoute
  '/events/fancy-dress': typeof EventsFancyDressRoute
  '/events/independence-day': typeof EventsIndependenceDayRoute
  '/events/primary-annual-day': typeof EventsPrimaryAnnualDayRoute
  '/events/primary-sports-day': typeof EventsPrimarySportsDayRoute
  '/events/project-day': typeof EventsProjectDayRoute
  '/events/republic-day': typeof EventsRepublicDayRoute
  '/events/sports-day': typeof EventsSportsDayRoute
  '/events/vidhya-pravesh': typeof EventsVidhyaPraveshRoute
  '/life/achievements': typeof LifeAchievementsRoute
  '/life/gallery': typeof LifeGalleryRoute
  '/life/infrastructure': typeof LifeInfrastructureRoute
  '/life/student-clubs': typeof LifeStudentClubsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alumni-connect': typeof AlumniConnectRoute
  '/contact': typeof ContactRoute
  '/mandatory-disclosure': typeof MandatoryDisclosureRoute
  '/about/advisory-board': typeof AboutAdvisoryBoardRoute
  '/about/facilities': typeof AboutFacilitiesRoute
  '/about/founders-vision': typeof AboutFoundersVisionRoute
  '/about/history': typeof AboutHistoryRoute
  '/about/managing-committee': typeof AboutManagingCommitteeRoute
  '/about/principals-message': typeof AboutPrincipalsMessageRoute
  '/about/testimonials': typeof AboutTestimonialsRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/academics/activity-schedule': typeof AcademicsActivityScheduleRoute
  '/academics/curriculum': typeof AcademicsCurriculumRoute
  '/academics/examination': typeof AcademicsExaminationRoute
  '/academics/method-of-evaluation': typeof AcademicsMethodOfEvaluationRoute
  '/academics/online-learning': typeof AcademicsOnlineLearningRoute
  '/academics/teaching-methodology': typeof AcademicsTeachingMethodologyRoute
  '/admissions/faqs': typeof AdmissionsFaqsRoute
  '/admissions/fee': typeof AdmissionsFeeRoute
  '/admissions/online-registration': typeof AdmissionsOnlineRegistrationRoute
  '/admissions/portal': typeof AdmissionsPortalRoute
  '/admissions/uniform': typeof AdmissionsUniformRoute
  '/events/akshara-abhyas': typeof EventsAksharaAbhyasRoute
  '/events/annual-day': typeof EventsAnnualDayRoute
  '/events/fancy-dress': typeof EventsFancyDressRoute
  '/events/independence-day': typeof EventsIndependenceDayRoute
  '/events/primary-annual-day': typeof EventsPrimaryAnnualDayRoute
  '/events/primary-sports-day': typeof EventsPrimarySportsDayRoute
  '/events/project-day': typeof EventsProjectDayRoute
  '/events/republic-day': typeof EventsRepublicDayRoute
  '/events/sports-day': typeof EventsSportsDayRoute
  '/events/vidhya-pravesh': typeof EventsVidhyaPraveshRoute
  '/life/achievements': typeof LifeAchievementsRoute
  '/life/gallery': typeof LifeGalleryRoute
  '/life/infrastructure': typeof LifeInfrastructureRoute
  '/life/student-clubs': typeof LifeStudentClubsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alumni-connect': typeof AlumniConnectRoute
  '/contact': typeof ContactRoute
  '/mandatory-disclosure': typeof MandatoryDisclosureRoute
  '/about/advisory-board': typeof AboutAdvisoryBoardRoute
  '/about/facilities': typeof AboutFacilitiesRoute
  '/about/founders-vision': typeof AboutFoundersVisionRoute
  '/about/history': typeof AboutHistoryRoute
  '/about/managing-committee': typeof AboutManagingCommitteeRoute
  '/about/principals-message': typeof AboutPrincipalsMessageRoute
  '/about/testimonials': typeof AboutTestimonialsRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/academics/activity-schedule': typeof AcademicsActivityScheduleRoute
  '/academics/curriculum': typeof AcademicsCurriculumRoute
  '/academics/examination': typeof AcademicsExaminationRoute
  '/academics/method-of-evaluation': typeof AcademicsMethodOfEvaluationRoute
  '/academics/online-learning': typeof AcademicsOnlineLearningRoute
  '/academics/teaching-methodology': typeof AcademicsTeachingMethodologyRoute
  '/admissions/faqs': typeof AdmissionsFaqsRoute
  '/admissions/fee': typeof AdmissionsFeeRoute
  '/admissions/online-registration': typeof AdmissionsOnlineRegistrationRoute
  '/admissions/portal': typeof AdmissionsPortalRoute
  '/admissions/uniform': typeof AdmissionsUniformRoute
  '/events/akshara-abhyas': typeof EventsAksharaAbhyasRoute
  '/events/annual-day': typeof EventsAnnualDayRoute
  '/events/fancy-dress': typeof EventsFancyDressRoute
  '/events/independence-day': typeof EventsIndependenceDayRoute
  '/events/primary-annual-day': typeof EventsPrimaryAnnualDayRoute
  '/events/primary-sports-day': typeof EventsPrimarySportsDayRoute
  '/events/project-day': typeof EventsProjectDayRoute
  '/events/republic-day': typeof EventsRepublicDayRoute
  '/events/sports-day': typeof EventsSportsDayRoute
  '/events/vidhya-pravesh': typeof EventsVidhyaPraveshRoute
  '/life/achievements': typeof LifeAchievementsRoute
  '/life/gallery': typeof LifeGalleryRoute
  '/life/infrastructure': typeof LifeInfrastructureRoute
  '/life/student-clubs': typeof LifeStudentClubsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alumni-connect'
    | '/contact'
    | '/mandatory-disclosure'
    | '/about/advisory-board'
    | '/about/facilities'
    | '/about/founders-vision'
    | '/about/history'
    | '/about/managing-committee'
    | '/about/principals-message'
    | '/about/testimonials'
    | '/about/vision-mission'
    | '/academics/activity-schedule'
    | '/academics/curriculum'
    | '/academics/examination'
    | '/academics/method-of-evaluation'
    | '/academics/online-learning'
    | '/academics/teaching-methodology'
    | '/admissions/faqs'
    | '/admissions/fee'
    | '/admissions/online-registration'
    | '/admissions/portal'
    | '/admissions/uniform'
    | '/events/akshara-abhyas'
    | '/events/annual-day'
    | '/events/fancy-dress'
    | '/events/independence-day'
    | '/events/primary-annual-day'
    | '/events/primary-sports-day'
    | '/events/project-day'
    | '/events/republic-day'
    | '/events/sports-day'
    | '/events/vidhya-pravesh'
    | '/life/achievements'
    | '/life/gallery'
    | '/life/infrastructure'
    | '/life/student-clubs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alumni-connect'
    | '/contact'
    | '/mandatory-disclosure'
    | '/about/advisory-board'
    | '/about/facilities'
    | '/about/founders-vision'
    | '/about/history'
    | '/about/managing-committee'
    | '/about/principals-message'
    | '/about/testimonials'
    | '/about/vision-mission'
    | '/academics/activity-schedule'
    | '/academics/curriculum'
    | '/academics/examination'
    | '/academics/method-of-evaluation'
    | '/academics/online-learning'
    | '/academics/teaching-methodology'
    | '/admissions/faqs'
    | '/admissions/fee'
    | '/admissions/online-registration'
    | '/admissions/portal'
    | '/admissions/uniform'
    | '/events/akshara-abhyas'
    | '/events/annual-day'
    | '/events/fancy-dress'
    | '/events/independence-day'
    | '/events/primary-annual-day'
    | '/events/primary-sports-day'
    | '/events/project-day'
    | '/events/republic-day'
    | '/events/sports-day'
    | '/events/vidhya-pravesh'
    | '/life/achievements'
    | '/life/gallery'
    | '/life/infrastructure'
    | '/life/student-clubs'
  id:
    | '__root__'
    | '/'
    | '/alumni-connect'
    | '/contact'
    | '/mandatory-disclosure'
    | '/about/advisory-board'
    | '/about/facilities'
    | '/about/founders-vision'
    | '/about/history'
    | '/about/managing-committee'
    | '/about/principals-message'
    | '/about/testimonials'
    | '/about/vision-mission'
    | '/academics/activity-schedule'
    | '/academics/curriculum'
    | '/academics/examination'
    | '/academics/method-of-evaluation'
    | '/academics/online-learning'
    | '/academics/teaching-methodology'
    | '/admissions/faqs'
    | '/admissions/fee'
    | '/admissions/online-registration'
    | '/admissions/portal'
    | '/admissions/uniform'
    | '/events/akshara-abhyas'
    | '/events/annual-day'
    | '/events/fancy-dress'
    | '/events/independence-day'
    | '/events/primary-annual-day'
    | '/events/primary-sports-day'
    | '/events/project-day'
    | '/events/republic-day'
    | '/events/sports-day'
    | '/events/vidhya-pravesh'
    | '/life/achievements'
    | '/life/gallery'
    | '/life/infrastructure'
    | '/life/student-clubs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlumniConnectRoute: typeof AlumniConnectRoute
  ContactRoute: typeof ContactRoute
  MandatoryDisclosureRoute: typeof MandatoryDisclosureRoute
  AboutAdvisoryBoardRoute: typeof AboutAdvisoryBoardRoute
  AboutFacilitiesRoute: typeof AboutFacilitiesRoute
  AboutFoundersVisionRoute: typeof AboutFoundersVisionRoute
  AboutHistoryRoute: typeof AboutHistoryRoute
  AboutManagingCommitteeRoute: typeof AboutManagingCommitteeRoute
  AboutPrincipalsMessageRoute: typeof AboutPrincipalsMessageRoute
  AboutTestimonialsRoute: typeof AboutTestimonialsRoute
  AboutVisionMissionRoute: typeof AboutVisionMissionRoute
  AcademicsActivityScheduleRoute: typeof AcademicsActivityScheduleRoute
  AcademicsCurriculumRoute: typeof AcademicsCurriculumRoute
  AcademicsExaminationRoute: typeof AcademicsExaminationRoute
  AcademicsMethodOfEvaluationRoute: typeof AcademicsMethodOfEvaluationRoute
  AcademicsOnlineLearningRoute: typeof AcademicsOnlineLearningRoute
  AcademicsTeachingMethodologyRoute: typeof AcademicsTeachingMethodologyRoute
  AdmissionsFaqsRoute: typeof AdmissionsFaqsRoute
  AdmissionsFeeRoute: typeof AdmissionsFeeRoute
  AdmissionsOnlineRegistrationRoute: typeof AdmissionsOnlineRegistrationRoute
  AdmissionsPortalRoute: typeof AdmissionsPortalRoute
  AdmissionsUniformRoute: typeof AdmissionsUniformRoute
  EventsAksharaAbhyasRoute: typeof EventsAksharaAbhyasRoute
  EventsAnnualDayRoute: typeof EventsAnnualDayRoute
  EventsFancyDressRoute: typeof EventsFancyDressRoute
  EventsIndependenceDayRoute: typeof EventsIndependenceDayRoute
  EventsPrimaryAnnualDayRoute: typeof EventsPrimaryAnnualDayRoute
  EventsPrimarySportsDayRoute: typeof EventsPrimarySportsDayRoute
  EventsProjectDayRoute: typeof EventsProjectDayRoute
  EventsRepublicDayRoute: typeof EventsRepublicDayRoute
  EventsSportsDayRoute: typeof EventsSportsDayRoute
  EventsVidhyaPraveshRoute: typeof EventsVidhyaPraveshRoute
  LifeAchievementsRoute: typeof LifeAchievementsRoute
  LifeGalleryRoute: typeof LifeGalleryRoute
  LifeInfrastructureRoute: typeof LifeInfrastructureRoute
  LifeStudentClubsRoute: typeof LifeStudentClubsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni-connect': {
      id: '/alumni-connect'
      path: '/alumni-connect'
      fullPath: '/alumni-connect'
      preLoaderRoute: typeof AlumniConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mandatory-disclosure': {
      id: '/mandatory-disclosure'
      path: '/mandatory-disclosure'
      fullPath: '/mandatory-disclosure'
      preLoaderRoute: typeof MandatoryDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/advisory-board': {
      id: '/about/advisory-board'
      path: '/about/advisory-board'
      fullPath: '/about/advisory-board'
      preLoaderRoute: typeof AboutAdvisoryBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/facilities': {
      id: '/about/facilities'
      path: '/about/facilities'
      fullPath: '/about/facilities'
      preLoaderRoute: typeof AboutFacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/founders-vision': {
      id: '/about/founders-vision'
      path: '/about/founders-vision'
      fullPath: '/about/founders-vision'
      preLoaderRoute: typeof AboutFoundersVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/history': {
      id: '/about/history'
      path: '/about/history'
      fullPath: '/about/history'
      preLoaderRoute: typeof AboutHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/managing-committee': {
      id: '/about/managing-committee'
      path: '/about/managing-committee'
      fullPath: '/about/managing-committee'
      preLoaderRoute: typeof AboutManagingCommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/principals-message': {
      id: '/about/principals-message'
      path: '/about/principals-message'
      fullPath: '/about/principals-message'
      preLoaderRoute: typeof AboutPrincipalsMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/testimonials': {
      id: '/about/testimonials'
      path: '/about/testimonials'
      fullPath: '/about/testimonials'
      preLoaderRoute: typeof AboutTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/vision-mission': {
      id: '/about/vision-mission'
      path: '/about/vision-mission'
      fullPath: '/about/vision-mission'
      preLoaderRoute: typeof AboutVisionMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/activity-schedule': {
      id: '/academics/activity-schedule'
      path: '/academics/activity-schedule'
      fullPath: '/academics/activity-schedule'
      preLoaderRoute: typeof AcademicsActivityScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/curriculum': {
      id: '/academics/curriculum'
      path: '/academics/curriculum'
      fullPath: '/academics/curriculum'
      preLoaderRoute: typeof AcademicsCurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/examination': {
      id: '/academics/examination'
      path: '/academics/examination'
      fullPath: '/academics/examination'
      preLoaderRoute: typeof AcademicsExaminationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/method-of-evaluation': {
      id: '/academics/method-of-evaluation'
      path: '/academics/method-of-evaluation'
      fullPath: '/academics/method-of-evaluation'
      preLoaderRoute: typeof AcademicsMethodOfEvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/online-learning': {
      id: '/academics/online-learning'
      path: '/academics/online-learning'
      fullPath: '/academics/online-learning'
      preLoaderRoute: typeof AcademicsOnlineLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/teaching-methodology': {
      id: '/academics/teaching-methodology'
      path: '/academics/teaching-methodology'
      fullPath: '/academics/teaching-methodology'
      preLoaderRoute: typeof AcademicsTeachingMethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/faqs': {
      id: '/admissions/faqs'
      path: '/admissions/faqs'
      fullPath: '/admissions/faqs'
      preLoaderRoute: typeof AdmissionsFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/fee': {
      id: '/admissions/fee'
      path: '/admissions/fee'
      fullPath: '/admissions/fee'
      preLoaderRoute: typeof AdmissionsFeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/online-registration': {
      id: '/admissions/online-registration'
      path: '/admissions/online-registration'
      fullPath: '/admissions/online-registration'
      preLoaderRoute: typeof AdmissionsOnlineRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/portal': {
      id: '/admissions/portal'
      path: '/admissions/portal'
      fullPath: '/admissions/portal'
      preLoaderRoute: typeof AdmissionsPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/uniform': {
      id: '/admissions/uniform'
      path: '/admissions/uniform'
      fullPath: '/admissions/uniform'
      preLoaderRoute: typeof AdmissionsUniformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/akshara-abhyas': {
      id: '/events/akshara-abhyas'
      path: '/events/akshara-abhyas'
      fullPath: '/events/akshara-abhyas'
      preLoaderRoute: typeof EventsAksharaAbhyasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/annual-day': {
      id: '/events/annual-day'
      path: '/events/annual-day'
      fullPath: '/events/annual-day'
      preLoaderRoute: typeof EventsAnnualDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/fancy-dress': {
      id: '/events/fancy-dress'
      path: '/events/fancy-dress'
      fullPath: '/events/fancy-dress'
      preLoaderRoute: typeof EventsFancyDressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/independence-day': {
      id: '/events/independence-day'
      path: '/events/independence-day'
      fullPath: '/events/independence-day'
      preLoaderRoute: typeof EventsIndependenceDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/primary-annual-day': {
      id: '/events/primary-annual-day'
      path: '/events/primary-annual-day'
      fullPath: '/events/primary-annual-day'
      preLoaderRoute: typeof EventsPrimaryAnnualDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/primary-sports-day': {
      id: '/events/primary-sports-day'
      path: '/events/primary-sports-day'
      fullPath: '/events/primary-sports-day'
      preLoaderRoute: typeof EventsPrimarySportsDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/project-day': {
      id: '/events/project-day'
      path: '/events/project-day'
      fullPath: '/events/project-day'
      preLoaderRoute: typeof EventsProjectDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/republic-day': {
      id: '/events/republic-day'
      path: '/events/republic-day'
      fullPath: '/events/republic-day'
      preLoaderRoute: typeof EventsRepublicDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/sports-day': {
      id: '/events/sports-day'
      path: '/events/sports-day'
      fullPath: '/events/sports-day'
      preLoaderRoute: typeof EventsSportsDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/vidhya-pravesh': {
      id: '/events/vidhya-pravesh'
      path: '/events/vidhya-pravesh'
      fullPath: '/events/vidhya-pravesh'
      preLoaderRoute: typeof EventsVidhyaPraveshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life/achievements': {
      id: '/life/achievements'
      path: '/life/achievements'
      fullPath: '/life/achievements'
      preLoaderRoute: typeof LifeAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life/gallery': {
      id: '/life/gallery'
      path: '/life/gallery'
      fullPath: '/life/gallery'
      preLoaderRoute: typeof LifeGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life/infrastructure': {
      id: '/life/infrastructure'
      path: '/life/infrastructure'
      fullPath: '/life/infrastructure'
      preLoaderRoute: typeof LifeInfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life/student-clubs': {
      id: '/life/student-clubs'
      path: '/life/student-clubs'
      fullPath: '/life/student-clubs'
      preLoaderRoute: typeof LifeStudentClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlumniConnectRoute: AlumniConnectRoute,
  ContactRoute: ContactRoute,
  MandatoryDisclosureRoute: MandatoryDisclosureRoute,
  AboutAdvisoryBoardRoute: AboutAdvisoryBoardRoute,
  AboutFacilitiesRoute: AboutFacilitiesRoute,
  AboutFoundersVisionRoute: AboutFoundersVisionRoute,
  AboutHistoryRoute: AboutHistoryRoute,
  AboutManagingCommitteeRoute: AboutManagingCommitteeRoute,
  AboutPrincipalsMessageRoute: AboutPrincipalsMessageRoute,
  AboutTestimonialsRoute: AboutTestimonialsRoute,
  AboutVisionMissionRoute: AboutVisionMissionRoute,
  AcademicsActivityScheduleRoute: AcademicsActivityScheduleRoute,
  AcademicsCurriculumRoute: AcademicsCurriculumRoute,
  AcademicsExaminationRoute: AcademicsExaminationRoute,
  AcademicsMethodOfEvaluationRoute: AcademicsMethodOfEvaluationRoute,
  AcademicsOnlineLearningRoute: AcademicsOnlineLearningRoute,
  AcademicsTeachingMethodologyRoute: AcademicsTeachingMethodologyRoute,
  AdmissionsFaqsRoute: AdmissionsFaqsRoute,
  AdmissionsFeeRoute: AdmissionsFeeRoute,
  AdmissionsOnlineRegistrationRoute: AdmissionsOnlineRegistrationRoute,
  AdmissionsPortalRoute: AdmissionsPortalRoute,
  AdmissionsUniformRoute: AdmissionsUniformRoute,
  EventsAksharaAbhyasRoute: EventsAksharaAbhyasRoute,
  EventsAnnualDayRoute: EventsAnnualDayRoute,
  EventsFancyDressRoute: EventsFancyDressRoute,
  EventsIndependenceDayRoute: EventsIndependenceDayRoute,
  EventsPrimaryAnnualDayRoute: EventsPrimaryAnnualDayRoute,
  EventsPrimarySportsDayRoute: EventsPrimarySportsDayRoute,
  EventsProjectDayRoute: EventsProjectDayRoute,
  EventsRepublicDayRoute: EventsRepublicDayRoute,
  EventsSportsDayRoute: EventsSportsDayRoute,
  EventsVidhyaPraveshRoute: EventsVidhyaPraveshRoute,
  LifeAchievementsRoute: LifeAchievementsRoute,
  LifeGalleryRoute: LifeGalleryRoute,
  LifeInfrastructureRoute: LifeInfrastructureRoute,
  LifeStudentClubsRoute: LifeStudentClubsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
